import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const globalCounter = useSelector((state) => state.counter.counter);
  const dispatch = useDispatch();

  const handleIncrement = (e) => {
    dispatch({
      type: "counter/increment",
      payload: e,
    });
  };
  const handleDecrement = (e) => {
    dispatch({
      type: "counter/decrement",
      payload: e,
    });
  };

  return (
    <div>
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>counter </h1>
        <h4>{globalCounter}</h4>
        <button onClick={() => handleIncrement(globalCounter)}>incrment</button>
        <button onClick={() => handleDecrement(globalCounter)}>
          decrement
        </button>
      </main>
    </div>
  );
}
